name: topshottimer
description: TopShot Timer

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  # Used to manipulate a variable like capitalization
  basic_utils: ^3.0.2
  # Hash user passwords
  crypto: ^2.1.2
  flutter_session: ^0.1.1
  shared_preferences: ^0.5.12+4
  audio_session: ^0.0.11
  just_audio: ^0.5.7
  flutter_launcher_name: ^0.0.1
  permission_handler: ^5.0.1+1
  # Adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # Allows the user to tap away from the keyboard to dismiss it
  keyboard_dismisser: ^1.0.2
  # Checks if user has internet or not
  connectivity: ^2.0.2
  # In conjuntion with connectivity it checks for internet
  data_connection_checker: ^0.3.4
  # For internet and enabling or disabling buttons and solves setstate with dialogs
  get: ^3.24.0
  # Bottom 3 are for subscriptions
  rflutter_alert: ^1.0.3
  url_launcher: ^5.7.10
  # For RevenuCat
  purchases_flutter: ^3.2.2
  flutter_audio_recorder: 0.5.5
  admob_flutter: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "TopShot Timer"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/audios/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Digital-7
      fonts:
        - asset: assets/digital-7.ttf
    - family: Montserrat-Regular
      fonts:
        - asset: assets/Montserrat-Regular.ttf
    - family: Montserrat-Bold
      fonts:
        - asset: assets/Montserrat-Bold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages